services:
  web-api:
    image: ecommerce-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5242:8080"
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ecommerce_db;Username=postgres;Password=YourStrongPasswordHere
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPasswordHere
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: